replicaCount: 2

image:
  repository: 536697262404.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
  tag: "5d07ab94297354d6d080216e99e29ed4a0364496"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 3000
