replicaCount: 2

image:
  repository: 536697262404.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
  tag: "555ce18455e8efbc44dabd238facd02bd88fb0e2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 3000
