replicaCount: 2

image:
  repository: 536697262404.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
  tag: "768c2ebf509fb7ab44fd4ef51b5507990b001858"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 3000
