name: CI Pipeline

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    env:
      ECR_REPO: ${{ secrets.ECR_REPO }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${ECR_REPO}:${IMAGE_TAG} -t ${ECR_REPO}:latest -f Dockerfile .

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0

      - name: Push Image to ECR
        run: |
          docker push ${ECR_REPO}:${IMAGE_TAG}
          docker push ${ECR_REPO}:latest

      - name: Update Helm values with new image tag
        run: |
          sed -i "s/^  tag: .*/  tag: \"${IMAGE_TAG}\"/" helm/nodejs-app/values.yaml

      - name: Commit updated Helm values
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/nodejs-app/values.yaml
          git diff --cached --quiet && exit 0
          git commit -m "Update image tag to ${IMAGE_TAG}"
          git push
